language: node_js
node_js:
- '0.10'
git:
  depth: 10
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower gulp-cli
- npm install -q
- bower install --force
- bower install --force
script: gulp
deploy:
  provider: npm
  email: adrien.crivelli@gmail.com
  api_key:
    secure: d22AeEluMuXw9FXXwmtTMyzXVH4ywcuiu1vwbfriEkpcPEMGbB/y7xKQ42Q64AoxwjtKKlMzFSjLfI6iFhoAzttMnQ0lQU/RIPF9g+P7vCAdjxVHr40Cu5JGMuLMgy/pRQXVNdEEMDSChIHUCd7rfStyqvR+adourvJva7aypMVu4fyrEL9KZNYVaOXgEiDrO3MrIJk5/DWynyVMcjGcwZQ+7LOoRdqdTxjdDvIJri0ztZljfKgJD/J6jKAPEj1T3QX1GDlz2emWp4A5YkTUSPWcPbM5GI5zuxdHyPhSECqbh/eTPICH9HNqEG3h5jOEpYamho5exVYz9lTonlMuowVQiTOEQZGim8vxqNWyHALaMdqiHWtNi7DHRrCHlld214RMTDKT0qpdr7FeZicAKqbn/JaUEaN6c6VhPJPfjm7RFncFcq1BP/kGpBloYDfXU3Wr6PVvVoFYc6D1mHCah+/iUCmPXNvuC7abYooUS5zUY0G9PjW9MSVVWMWD5/uCeXBQDg7qS5RWM5DdXxnp4BTQzggZbvkVTEPZi67b3PK1KlTEFGueysIvJgkNezJmKCYOVL+hU6HeZ9RKLDctLY8SoqBjRC2lK3njXmq8/CPL9MF4CD2Bp6L6DPf2utU8cZhZM/vstdpvi+7eA9H2WLwdv7QmwRnsWTGvBG3TnpY=
  on:
    tags: true
    repo: angular-ui/ui-event
